# Numpy

Welcome to Numpy a package widely used in the data science community. 
In this assignment, you will:
* Learn to use Numpy, a package which let us work efficiently with arrays and matrices in Python.


#### Why are we using Numpy? 

* Extra features required by Python :
* fast, multidimensional arrays
* libraries of reliable, tested scientific functions
* plotting tools
* NumPy is at the core of nearly every scientific Python application or module since it provides a fast N-d array datatype that can be manipulated in a vectorized form. 

## Load package
* Let's import Numpy as np. This lets us use the shortcut np to refer to Numpy..

In [1]:
import numpy as np


**Our first Numpy array. We can start by creating a list and converting in to an array**: 

In [155]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

** x is our first Numpy array. We can pass the list directly**:

In [3]:
y = np.array([4, 5, 6])
y


array([4, 5, 6])

**Multidimensional arrays by passing in a list of lists.
(We passed in two lists with three elements each, and we get a two by three array.)**: 

* Create a numpy array m  with the vectors: [7, 8, 9] and  [10, 11, 12]
* Check the dimensions by using the shape attribute


In [5]:
m = #Insert code here
print("m: ", m)
#Check the dimensions by using the shape attribute:
#Insert code here


m:  [[ 7  8  9]
 [10 11 12]]


(2, 3)

**Number of rows of array**: 

In [33]:
m = np.array([[7, 8, 9], [10, 11, 12]])
#check the number of rows with the len function:
#Insert code here


2

In [34]:
#check the number of rows with the shape attribute:
#Insert code here


2

### 1 - arange function:
We pass in a start, a stop, and a step size, 
and it returns evenly spaced values within a given interval.

* Create a numpy array n that start at 0 count up by 2 and stop before 30


In [6]:
n = #Insert code here
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 2- reshape method:
Suppose we wanted to convert this array of numbers to a three by five array. 
We can use reshape to do that.:

* Reshape array to be 3x5

In [7]:
n = #Insert code here
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### 3- linspace function:
It is similar to arange, except we tell it how many numbers we want returned, and it will split up the interval according:

* Create numpy array o returning 9 evenly spaced values from 0 to 4


In [20]:
o = # Insert code here
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

* Now please resize to change the dimensions in place to 3x3:

In [21]:
o.#Insert code here
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

## Built-in functions and shortcuts for creating arrays.



### 1- ones function:
Returns an array of ones
* Create an array of ones with dimensions 3x2 and after multiply per 10


In [156]:
#Insert code here

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

### 2- zeros function:
Returns an array of zeros

* Create an array of zeros with dimensions 2x3


In [16]:
#Insert code here

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3- eye function:
Returns an array with ones on the diagonal and zeros everywhere else

* Create an identity matrix with dimensions 3x3


In [17]:
#Insert code here

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4- diag function:
Constructs a diagonal array

* Create diagonal array based on previous y array 


In [19]:
print ("y:" ,y)
#Insert code here

y: [4 5 6]


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

### 5- repeat function:
Return an array with repeated values

* Repeat the array [1,2,3] three times.


In [23]:
#Insert code here


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Notice the difference when we pass in a repeated list:

* Multiply the list [1,2,3] per 3 and convert it in a numpy array.


In [24]:
#Insert code here


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

### 6- vstack function:
Return a array stack it vertically

*  Stack the array p vertically with itself multiplied by 2.



In [30]:
p = np.ones([2, 3], int) 
2*p
#Insert code here

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

### 7- hstack function:
Return an array stack it horizontally.

* Stack the previous array p horizontally with itself multiplied by 2.

In [32]:
#Insert code here

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations.



### NumPy operations are usually done on pairs of arrays on an element-by-element basis:

Hint: From previous exercises:

x =  [1 2 3]

y =  [4 5 6]

### elementwise addition:

* Calculate and print the result:   [1 2 3] + [4 5 6] = [5  7  9]

In [35]:
#Insert code here


[5 7 9]



### elementwise substraction:

* Calculate and print the result:   [1 2 3] - [4 5 6] = [-3 -3 -3]

In [36]:
#Insert code here


[-3 -3 -3]



### elementwise multiplication:

* Calculate and print the result:   [1 2 3] * [4 5 6] = [4  10  18]

In [37]:
#Insert code here

[ 4 10 18]



### elementwise division:

* Calculate and print the result: [1 2 3] / [4 5 6] = [0.25  0.4  0.5]


In [38]:
#Insert code here

[0.25 0.4  0.5 ]



### elementwise power:

*  Calculate and print the result: [1 2 3] ^2 =  [1 4 9]

In [39]:
#Insert code here

[1 4 9]



### dot product function (linear algebra):

* Calculate and print the dot product between x and y:  1x4 + 2x5 + 3x6

In [40]:
#Insert code here

32


###  Transpose of an array using the t method: 
Swaps the rows and columns.

* Transpose z

In [47]:
z = np.array([y, y**2])
z

z.shape

#Insert code here

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])


####  transpose function: 

* Now use the np.transpose function with z


In [49]:
#np.transpose function:
z = np.array([y, y**2])
z

#Insert code

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

### dtype class:
Return type of the data (integer, float, Python object, etc.)

* Show z type of data

* With astype, cast an array to a different type ; float. 

In [50]:
#Insert code here

dtype('int32')

In [52]:
# with astype, cast an array to a different type. 

z = #Insert code here
z.dtype


dtype('float32')

## Math functions.

NumPy has quite a few useful  mathematical and statistical functions for finding minimum: min, maximum: max, standard deviation: std , sum, mean, indexes of maximum and minimum value: argmax and argmin, etc. from the given elements in the array.

* Calculate the required functions in each comment:

Hint:  a = np.array([-4, -2, 1, 3, 5])


In [54]:

a = np.array([-4, -2, 1, 3, 5])

#sum of the values of the array
#Insert code here


3

In [58]:
# maximum of the values of the array
#Insert code here


5

In [59]:
# minimum of the values of the array
#Insert code here


-4

In [61]:
# mean of the values of the array
#Insert code here


0.6

In [62]:
# standard deviation of the values of the array
#Insert code here


3.2619012860600183

In [64]:
# argmax: index of a maximum value

#Insert code here

4

In [65]:
# argmin: index of the minimum value
#Insert code here


0

## Indexing and slicing



We can use bracket notation to get the value at a particular index, 
and the colon notation to get a range.
The notation is start and stepsize.
Specifying the starting or ending index is not necessary. 


In [67]:
s = np.arange(13)**2 #array with the squares of 0 through 12. 
print("s: " ,s)

s[0], s[4], s[-1]



s:  [  0   1   4   9  16  25  36  49  64  81 100 121 144]


(0, 16, 144)

* For our first example (s array), Take a look at the range starting from index one and 
stopping before index five



In [69]:
#Insert code here

array([ 1,  4,  9, 16], dtype=int32)

We can also use negatives to count back from the end of the array. 

* Get a slice of the last four elements of the array.

In [71]:
#Insert code here

array([ 81, 100, 121, 144], dtype=int32)

* Starting fifth from the end to the beginning of the array and counting backwards by two.

In [74]:
# Remember s:[  0   1   4   9  16  25  36  49  64  81 100 121 144]
#Insert code here

array([64, 36, 16,  4,  0], dtype=int32)

When the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

* Reverse the array s


In [7]:
#Insert code here


array([144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0],
      dtype=int32)

In [75]:
r = np.arange(36)
r.resize((6, 6)) # two dimensional array, 0 to 35. 
r   

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

* Use colon notation to get a slice of the third row and 
columns three to six. 

In [80]:
#Insert code here

array([14, 15, 16, 17])


We can also do something like get the first two rows and 
all of the columns except the last.



In [78]:
#Insert code here

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])


Select every second element from the last row.



In [81]:
#Insert code here

array([30, 32, 34])

We can also use the bracket operator to do conditional indexing and assignment.

* Select elements of array r that are greater than 30.


In [83]:
#Insert code here


array([31, 32, 33, 34, 35])

We can also use the bracket operator to do conditional indexing and assignment.

* Take elements of array r that are greater than 30 and assign them to the new value = 30.


In [86]:
#Insert code here
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In numpy the copy is by reference not by value, what does it mean? when you copy an array to another variable the changes in this variable affect the original array.
Example: 
First, let's create a new array r2, which is a slice of the array r. Now, let's set all the elements of this array to zero.


In [88]:
r2 = r[:3,:3]
r2

r2[:] = 0
r2

r # When we look at the original array r,  we can see that the slice in r has also been changed. 

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

If we wish to create a copy of the r array that will not change the original array, 
we can use the copy method:

* Use the copy method from the r array to r_copy:

In [88]:
r_copy = #Insert code here
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

We can see that if we change the values of all the elements in r_copy to 5, 
the original array r remains unchanged.




In [90]:
r_copy[:] = 5
print(r_copy, '\n')
print(r)


[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]



## Iterate over arrays.

We can iterate by row by typing for row in test, for example.

In [91]:
test = np.random.randint(0, 10, (4,3)) #four by three array of random numbers, from zero through nine
test

array([[0, 4, 1],
       [2, 3, 9],
       [9, 4, 2],
       [5, 4, 4]])

In [92]:
for row in test:
    print(row)

[0 4 1]
[2 3 9]
[9 4 2]
[5 4 4]


We can iterate by row index by using the length function on test, 
which returns the number of rows.


In [97]:
for i in #Insert code here
    print (str(i) + ": " + str(test[i]))

0: [0 4 1]
1: [2 3 9]
2: [9 4 2]
3: [5 4 4]



We can combine these two ways of iterating by using enumerate, 
which gives us the row and the index of the row.

* Make a new array, test2 using enumerate() with the test variable

In [109]:
test2= #Insert code here
for i, row in test2:
    print('row', i, 'is', row)


row 0 is [0 4 1]
row 1 is [2 3 9]
row 2 is [9 4 2]
row 3 is [5 4 4]



If we wish to iterate through both arrays, we can use zip.

* Use zip with test and test2

In [112]:
test2 = test**2
for i, j in #Insert code here
    print(i,'+',j,'=',i+j)

[0 4 1] + [ 0 16  1] = [ 0 20  2]
[2 3 9] + [ 4  9 81] = [ 6 12 90]
[9 4 2] + [81 16  4] = [90 20  6]
[5 4 4] + [25 16 16] = [30 20 20]



## File I/O.

Save in a text file and a numpy file format:

* Save test2 in a file called datasaved.npy using the function save.

In [124]:
#Insert code here


In [127]:
#load the file datasaved.npy in the variable test_from_file and print it.

test_from_file = #Insert code here
print(test_from_file)

[[ 0 16  1]
 [ 4  9 81]
 [81 16  4]
 [25 16 16]]


In [132]:
#Save test in a file called datasaved.txt using the function savetxt
#Insert code here

In [137]:
#Use the function genfromtxt to load the file datasaved.txt in the variable data and print it.
# delimiter= ' ' and skip_header= 0
data = #Insert code here
print(data)

[[0. 4. 1.]
 [2. 3. 9.]
 [9. 4. 2.]
 [5. 4. 4.]]



## Sorting

Acts in array himself (method):

* Sort the array data using the method sort 

In [140]:
#Insert code here
data

array([[0., 1., 4.],
       [2., 3., 9.],
       [2., 4., 9.],
       [4., 4., 5.]])


Numpy function sort:
* Sort the array data using the numpy function

In [141]:
#Insert code here 

array([[0., 1., 4.],
       [2., 3., 9.],
       [2., 4., 9.],
       [4., 4., 5.]])


Numpy function argsort:

* Return the indices that would sort the data array. 

In [150]:
s= data.#Insert code here
s

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

* Return the indices that would sort the data array in descend order 
* Hint: Descend order: Negate the array

In [151]:
s= #Insert code here
s

array([[2, 1, 0],
       [2, 1, 0],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [154]:
#Order data array in descend order 
result= #Insert code here
result

array([[4., 1., 0.],
       [9., 3., 2.],
       [9., 4., 2.],
       [5., 4., 4.]])