# Numpy

Welcome to Numpy a package widely used in the data science community. 
In this assignment, you will:
* Learn to use Numpy, a package which let us work efficiently with arrays and matrices in Python.


#### Why are we using Numpy? 

* Extra features required by Python :
* fast, multidimensional arrays
* libraries of reliable, tested scientific functions
* plotting tools
* NumPy is at the core of nearly every scientific Python application or module since it provides a fast N-d array datatype that can be manipulated in a vectorized form. 

## Load package
* Let's import Numpy as np. This lets us use the shortcut np to refer to Numpy..

In [1]:
import numpy as np


**Our first Numpy array. We can start by creating a list and converting in to an array**: 

In [155]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

** x is our first Numpy array. We can pass the list directly**:

In [3]:
y = np.array([4, 5, 6])
y


array([4, 5, 6])

**Multidimensional arrays by passing in a list of lists.
(We passed in two lists with three elements each, and we get a two by three array.)**: 

In [5]:
m = np.array([[7, 8, 9], [10, 11, 12]])
print("m: ", m)
#Check the dimensions by using the shape attribute:
m.shape


m:  [[ 7  8  9]
 [10 11 12]]


(2, 3)

**Number of rows of array**: 

In [33]:
m = np.array([[7, 8, 9], [10, 11, 12]])
len(m)


2

In [34]:
m.shape[0]


2

### 1 - arange function:
We pass in a start, a stop, and a step size, 
and it returns evenly spaced values within a given interval.

In [6]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 2- reshape method:
Suppose we wanted to convert this array of numbers to a three by five array. 
We can use reshape to do that.:

In [7]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### 3- linspace function:
It is similar to arange, except we tell it how many numbers we want returned, and it will split up the interval according:


In [20]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

We can use resize to change the dimensions in place:

In [21]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

## Built-in functions and shortcuts for creating arrays.



### 1- ones function:
Returns an array of ones


In [156]:
np.ones((3, 2))*10

array([[10., 10.],
       [10., 10.],
       [10., 10.]])

### 2- zeros function:
Returns an array of zeros


In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3- eye function:
Returns an array with ones on the diagonal and zeros everywhere else


In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4- diag function:
Constructs a diagonal array


In [19]:
print ("y:" ,y)
np.diag(y)

y: [4 5 6]


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

### 5- repeat function:
Return an array with repeated values


In [23]:
np.repeat([1, 2, 3], 3)


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Notice the difference when we pass in a repeated list:


In [24]:
np.array([1, 2, 3] * 3)


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

### 6- vstack function:
Return a array stack it vertically



In [30]:
p = np.ones([2, 3], int) 
2*p
np.vstack([p, 2*p]) #create two arrays from p and stack it vertically with itself multiplied by 2.

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

### 7- hstack function:
Return an array stack it horizontally.

In [32]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations.



### NumPy operations are usually done on pairs of arrays on an element-by-element basis:

### elementwise addition:

In [35]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]


[5 7 9]



### elementwise substraction:

In [36]:
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]


[-3 -3 -3]



### elementwise multiplication:

In [37]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]

[ 4 10 18]



### elementwise division:

In [38]:
print(x / y) # elementwise division  [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[0.25 0.4  0.5 ]



### elementwise power:

In [39]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]



### dot product function (linear algebra):

In [40]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32


###  Transpose of an array using the t method: 
Swaps the rows and columns.

In [47]:
z = np.array([y, y**2])
z

z.shape

z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])


####  transpose function: 


In [49]:
#np.transpose function:
z = np.array([y, y**2])
z

np.transpose(z)

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

### dtype class:
Return type of the data (integer, float, Python object, etc.)



In [50]:
z.dtype

dtype('int32')

In [52]:
# with astype, cast an array to a different type. 

z = z.astype('f')
z.dtype


dtype('float32')

## Math functions.



In [54]:

a = np.array([-4, -2, 1, 3, 5])

#sum of the values of the array
a.sum()


3

In [58]:
# maximum of the values of the array
a.max()


5

In [59]:
# minimum of the values of the array
a.min()


-4

In [61]:
# mean of the values of the array
a.mean()


0.6

In [62]:
# standard deviation of the values of the array
a.std()


3.2619012860600183

In [64]:
# argmax: index of a maximum value

a.argmax()

4

In [65]:
# argmin: indez of the minimum value
a.argmin()


0

## Indexing and slicing



We can use bracket notation to get the value at a particular index, 
and the colon notation to get a range.
The notation is start and stepsize.
Specifying the starting or ending index is not necessary. 


In [67]:
s = np.arange(13)**2 #array with the squares of 0 through 12. 
print("s: " ,s)

s[0], s[4], s[-1]



s:  [  0   1   4   9  16  25  36  49  64  81 100 121 144]


(0, 16, 144)

For our first example, let's take a look at the range starting from index one and 
stopping before index five



In [69]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

We can also use negatives to count back from the end of the array. 
Get a slice of the last four elements of the array.

In [71]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

Starting fifth from the end to the beginning of the array and counting backwards by two.

In [74]:
s[-5::-2]   # Remember s:[  0   1   4   9  16  25  36  49  64  81 100 121 144]

array([64, 36, 16,  4,  0], dtype=int32)

When the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:



In [ ]:
s[::-1]

In [75]:
r = np.arange(36)
r.resize((6, 6)) # two dimensional array, 0 to 35. 
r   

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use colon notation to get a slice of the third row and 
columns three to six. 

In [80]:
r[2, 2:]  

array([14, 15, 16, 17])


We can also do something like get the first two rows and 
all of the columns except the last.



In [78]:
r[:2, :-1]  

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])


Select every second element from the last row.



In [81]:
r[-1, ::2]

array([30, 32, 34])

We can also use the bracket operator to do conditional indexing and assignment.


In [83]:
r[r > 30]  #elements of array that are greater than 30. 


array([31, 32, 33, 34, 35])

We can also use the bracket operator to do conditional indexing and assignment.


In [86]:
r[r > 30] = 30 #take those elements within the array and assign them to a new value.
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In numpy the copy is by reference not by value, what does it mean? when you copy an array to another variable the changes in this variable affect the original array.
Example: 
First, let's create a new array r2, which is a slice of the array r. Now, let's set all the elements of this array to zero.


In [88]:
r2 = r[:3,:3]
r2

r2[:] = 0
r2

r # When we look at the original array r,  we can see that the slice in r has also been changed. 

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

If we wish to create a copy of the r array that will not change the original array, 
we can use the copy method:



In [88]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

We can see that if we change the values of all the elements in r_copy to 5, 
the original array r remains unchanged.




In [90]:
r_copy[:] = 5
print(r_copy, '\n')
print(r)


[[5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]



## Iterate over arrays.

We can iterate by row by typing for row in test, for example.

In [91]:
test = np.random.randint(0, 10, (4,3)) #four by three array of random numbers, from zero through nine
test

array([[0, 4, 1],
       [2, 3, 9],
       [9, 4, 2],
       [5, 4, 4]])

In [92]:
for row in test:
    print(row)

[0 4 1]
[2 3 9]
[9 4 2]
[5 4 4]


We can iterate by row index by using the length function on test, 
which returns the number of rows.


In [97]:
for i in range(len(test)):
    print (str(i) + ": " + str(test[i]))

0: [0 4 1]
1: [2 3 9]
2: [9 4 2]
3: [5 4 4]



We can combine these two ways of iterating by using enumerate, 
which gives us the row and the index of the row.

Let's make a new array, test2.

In [109]:
test2= enumerate(test)
for i, row in test2:
    print('row', i, 'is', row)


row 0 is [0 4 1]
row 1 is [2 3 9]
row 2 is [9 4 2]
row 3 is [5 4 4]



If we wish to iterate through both arrays, we can use zip.

In [112]:
test2 = test**2
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[0 4 1] + [ 0 16  1] = [ 0 20  2]
[2 3 9] + [ 4  9 81] = [ 6 12 90]
[9 4 2] + [81 16  4] = [90 20  6]
[5 4 4] + [25 16 16] = [30 20 20]



## File I/O.

Save in a text file and a numpy file format:

In [124]:
np.save('datasaved.npy', test2)


In [127]:
test_from_file = np.load('datasaved.npy')
print(test_from_file)

[[ 0 16  1]
 [ 4  9 81]
 [81 16  4]
 [25 16 16]]


In [132]:
np.savetxt('datasaved.txt', test)

In [137]:
data = np.genfromtxt('datasaved.txt', delimiter=' ', skip_header=0)
print(data)

[[0. 4. 1.]
 [2. 3. 9.]
 [9. 4. 2.]
 [5. 4. 4.]]



## Sorting

Acts in array himself (method):

In [140]:
data.sort()
data

array([[0., 1., 4.],
       [2., 3., 9.],
       [2., 4., 9.],
       [4., 4., 5.]])


Numpy function:

In [141]:
np.sort(data)

array([[0., 1., 4.],
       [2., 3., 9.],
       [2., 4., 9.],
       [4., 4., 5.]])

In [150]:
s= data.argsort()
s

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)


Descend order: Negate the array

In [151]:
s= (-data).argsort()
s

array([[2, 1, 0],
       [2, 1, 0],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [154]:
result= -np.sort(-data)
result

array([[4., 1., 0.],
       [9., 3., 2.],
       [9., 4., 2.],
       [5., 4., 4.]])